---
apiVersion: v1
kind: Secret
metadata:
  name: ordersss80-app-repo
  namespace: devhub
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/ordersss80-app-backend-gitops
